#############################################################################
############################### CRUD POSITION ###############################

### Busca a posição do usuário

GET  http://localhost:3000/api/position/5f94c4e17738a2715cb007cc HTTP/1.1

### Registra posição do usuário

POST  http://localhost:3000/api/position HTTP/1.1
Content-Type: application/json

{
    "profile": "5f94c4e17738a2715cb007cc",
    "coordinates": [
        -122.5,
        37.7
    ]
}

### Atualiza a posição do usuário

PUT  http://localhost:3000/api/position/5f94c4e17738a2715cb007cc HTTP/1.1
Content-Type: application/json

{
    "coordinates": [
        -123.5,
        37.7
    ]
}

### Remove a posição do usuário

DELETE http://localhost:3000/api/position/5f94c4e17738a2715cb007cc HTTP/1.1